[package]
name = "d3r"
description = "dawd³ audio runtime"
version = "0.1.0"
edition = "2021"

[lib]
name = "dawd3_d3r"
crate-type = ["cdylib"]

[dependencies]
bitvec = "1.0.1"
cpal = "0.14.1"
env_logger = "0.9.3"
jni = "0.20.0"
log = "0.4.17"
